- hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install prerequisites for MongoDB
      apt:
        name: 
          - gnupg
          - wget
        state: present

    - name: Add universe repository (required for some packages)
      apt_repository:
        repo: 'ppa:ondrej/mysql-8.0'
        state: present

    - name: Update apt cache after adding new repositories
      apt:
        update_cache: yes

    - name: Install MySQL and fix missing dependencies
      apt:
        name: mysql-server
        state: present
        force_apt_get: yes
        allow_unauthenticated: yes

    - name: Download the MongoDB public GPG key
      get_url:
        url: https://www.mongodb.org/static/pgp/server-7.0.asc
        dest: /etc/apt/trusted.gpg.d/server-7.0.asc
        mode: '0644'

    - name: Create the list file for MongoDB
      copy:
        content: 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse'
        dest: /etc/apt/sources.list.d/mongodb-org-7.0.list
        mode: '0644'

    - name: Reload local package database
      apt:
        update_cache: yes

    - name: Install the mongosh package
      apt:
        name: mongodb-mongosh
        state: present
