- hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install prerequisites for MongoDB
      apt:
        name: 
          - gnupg
          - wget
        state: present

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Download the MongoDB public GPG key
      command: curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc
      register: mongodb_gpg_key

    - name: Add MongoDB public GPG key to trusted keys
      command: tee /etc/apt/trusted.gpg.d/server-7.0.asc
      stdin: "{{ mongodb_gpg_key.stdout }}"
      
    - name: Create the list file for MongoDB
      command:
        cmd: "echo 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse' | tee /etc/apt/sources.list.d/mongodb-org-7.0.list"
      args:
        creates: /etc/apt/sources.list.d/mongodb-org-7.0.list

    - name: Reload local package database
      apt:
        update_cache: yes

    - name: Install the mongosh package
      apt:
        name: mongodb-mongosh
        state: present
